import React, { useEffect, useState } from 'react';
import { Modal } from './Modal';
import { Button } from './Button';
import { LevelFailedModalProps } from '../types';

export const LevelFailedModal: React.FC<LevelFailedModalProps> = ({
  isOpen,
  onClose,
  level,
  geminiFeedback,
  onReplayLevel,
  onBackToSelect,
}) => {
  const [showFeedback, setShowFeedback] = useState(false);

  useEffect(() => {
    if (isOpen) {
      const timer = setTimeout(() => {
        setShowFeedback(true);
      }, 500); // Small delay before showing feedback
      return () => clearTimeout(timer);
    } else {
      setShowFeedback(false); // Reset when closed
    }
  }, [isOpen]);

  const footerContent = (
    <div className="flex flex-col sm:flex-row justify-center sm:justify-end gap-3 w-full">
      <Button variant="secondary" onClick={onBackToSelect}>
        Back to Level Select
      </Button>
      <Button variant="danger" onClick={onReplayLevel}>
        Retry Level
      </Button>
    </div>
  );

  return (
    <Modal isOpen={isOpen} onClose={onClose} title="Level Failed!" size="xl" footer={footerContent}>
      <div className="text-center p-4">
        <h2 className="text-4xl font-extrabold text-white mb-4">
          <span className="bg-clip-text text-transparent bg-gradient-to-r from-red-400 to-orange-400">
            {level.name}: Temporal Anomaly!
          </span>
        </h2>

        <div className="text-6xl mb-6" role="img" aria-label="Sad face emoji">
            😞
        </div>

        <div className="bg-red-900 bg-opacity-40 p-5 rounded-lg border border-red-700 mt-6 text-left">
          <h4 className="font-bold text-red-200 mb-2">Temporal Anomaly Report:</h4>
          <p className="text-red-100 text-sm italic">"{geminiFeedback || "The chronometer indicates a critical divergence. Recalibrating for another attempt is advised."}"</p>
          <p className="text-xs text-red-300 mt-3">
            <span className="font-semibold">Chronicler's Note:</span> Generated by Gemini AI based on your temporal journey.
          </p>
        </div>
      </div>
    </Modal>
  );
};