import React, { useEffect, useState } from 'react';
import { Modal } from './Modal';
import { Button } from './Button';
import { LevelCompleteModalProps } from '../types';

export const LevelCompleteModal: React.FC<LevelCompleteModalProps> = ({
  isOpen,
  onClose,
  level,
  timeTaken,
  rewindsUsed,
  starsEarned,
  geminiFeedback,
  onReplayLevel,
  onNextLevel,
  onBackToSelect,
  hasMoreLevels,
}) => {
  const [showFeedback, setShowFeedback] = useState(false);

  useEffect(() => {
    if (isOpen) {
      // Simulate fetching feedback after a short delay for dramatic effect
      const timer = setTimeout(() => {
        setShowFeedback(true);
      }, 1000); // Allow stars to show first
      return () => clearTimeout(timer);
    } else {
      setShowFeedback(false); // Reset when closed
    }
  }, [isOpen]);

  const formatTime = (seconds: number) => {
    const mins = Math.floor(seconds / 60);
    const secs = Math.floor(seconds % 60);
    const ms = Math.floor((seconds * 100) % 100);
    return `${mins.toString().padStart(2, '0')}:${secs.toString().padStart(2, '0')}.${ms.toString().padStart(2, '0')}`;
  };

  const renderStars = (count: number) => {
    const stars = [];
    for (let i = 0; i < 3; i++) {
      stars.push(
        <svg
          key={i}
          className={`w-10 h-10 ${
            i < count ? 'text-yellow-400 opacity-100' : 'text-gray-600 opacity-50'
          } transition-opacity duration-500 ease-in-out`}
          fill="currentColor"
          viewBox="0 0 20 20"
          xmlns="http://www.w3.org/2000/svg"
        >
          <path d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.538 1.118l-2.8-2.034a1 1 0 00-1.176 0l-2.8 2.034c-.783.57-1.838-.197-1.538-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.462a1 1 0 00.95-.69l1.07-3.292z"></path>
        </svg>
      );
    }
    return <div className="flex justify-center space-x-1">{stars}</div>;
  };

  const footerContent = (
    <div className="flex flex-col sm:flex-row justify-center sm:justify-end gap-3 w-full">
      <Button variant="secondary" onClick={onBackToSelect}>
        Back to Level Select
      </Button>
      <Button variant="outline" onClick={onReplayLevel}>
        Replay Level
      </Button>
      {hasMoreLevels && (
        <Button variant="primary" onClick={onNextLevel}>
          Next Level
        </Button>
      )}
    </div>
  );

  return (
    <Modal isOpen={isOpen} onClose={onClose} title="Level Complete!" size="xl" footer={footerContent}>
      <div className="text-center p-4">
        <h2 className="text-4xl font-extrabold text-white mb-4">
          <span className="bg-clip-text text-transparent bg-gradient-to-r from-purple-400 to-indigo-400">
            {level.name} Conquered!
          </span>
        </h2>

        <div className="mb-6">{renderStars(starsEarned)}</div>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-4 text-left mb-6">
          <div className="bg-gray-700 p-4 rounded-md shadow-inner">
            <h4 className="font-semibold text-gray-300">Time Taken:</h4>
            <p className="text-lg text-white font-bold">{formatTime(timeTaken)}</p>
          </div>
          <div className="bg-gray-700 p-4 rounded-md shadow-inner">
            <h4 className="font-semibold text-gray-300">Rewinds Used:</h4>
            <p className="text-lg text-white font-bold">{rewindsUsed}</p>
          </div>
        </div>

        {showFeedback && geminiFeedback && (
          <div className="bg-indigo-900 bg-opacity-40 p-5 rounded-lg border border-indigo-700 mt-6 text-left">
            <h4 className="font-bold text-indigo-200 mb-2">Temporal Anomaly Report:</h4>
            <p className="text-indigo-100 text-sm italic">"{geminiFeedback}"</p>
            <p className="text-xs text-indigo-300 mt-3">
              <span className="font-semibold">Chronicler's Note:</span> Generated by Gemini AI based on your performance.
            </p>
          </div>
        )}
      </div>
    </Modal>
  );
};